language: php

php:
    - 5.6
    - 7.0
    - 7.1

notifications:
    email: false

env:
    - TESTER_PHP_BIN="php"

matrix:
    include:
        - php: 7.0
          env: coverage="--coverage ./coverage.xml --coverage-src ./src" TESTER_PHP_BIN=phpdbg
    allow_failures:
        - php: 7.0
          env: coverage="--coverage ./coverage.xml --coverage-src ./src" TESTER_PHP_BIN=phpdbg
  
before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then phpenv config-rm xdebug.ini; fi
    - composer self-update

install:
    - composer install --no-interaction --prefer-source
    - wget https://gitlab.com/nexendrie/resources/raw/master/cs-ruleset.xml
  
script:
    - if [ "$TESTER_PHP_BIN" = "php" ]; then ./vendor/bin/parallel-lint src tests -e php,phpt; fi
    - if [ "$TESTER_PHP_BIN" = "php" ]; then ./vendor/bin/phpcs --extensions=php,phpt . --standard=cs-ruleset.xml --colors; fi
    - ./vendor/bin/run-tests -p $TESTER_PHP_BIN tests -s $coverage

after_script:
    - if [ "$coverage" != "" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi
    
after_failure:
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
